# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://wxmbaci:${{ secrets.PAT }}@github.com/shufflewzc/faker2.git"
          source_branch: "main"
          destination_repo: "https://username:${{ secrets.PAT }}@github.com/wxmbaci/clone_scripts.git"
          destination_branch: "faker2"

