# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "shufflewzc/faker2"
          source_branch: "main"
          destination_repo: "wxmbaci/clone_scripts"
          destination_branch: "faker2"

